### ISSUE TITLE
--no-dependencies install option errors out

### ISSUE THREAD

**Issue by ChristopherWilks** [nellore/rail#29]
python rail/releases/install_rail-rna-devel --no-dependencies
â Rail-RNA vdevel Installer
Rail-RNA can be installed for all users or just the current user.
    * Install for all users? [y/n]: n
Traceback (most recent call last):.
  File "/cm/shared/apps/python/2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cm/shared/apps/python/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "rail/releases/install_rail-rna-devel/__main__.py", line 90, in <module>
  File "/home-1/cwilks3@jhu.edu/rail/releases/install_rail-rna-devel/rna/driver/rna_installer.py", line 381, in install
  File "/cm/shared/apps/python/2.7.9/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "rail/releases/install_rail-rna-devel/dooplicity/tools.py", line 63, in cd
OSError: [Errno 2] No such file or directory: '/tmp/tmpxPjmQ4/samtools-1.2'

**Comment by nellore** [comment]
not anymore as of d84679708410ffcedc53f6adb6a753200be276e1!
